server:
  port: 8185
  connection-timeout: 5000
  tomcat:
    max-threads: 600  #--最大线程数---#
    min-spare-threads: 20 #---允许空先线程数----#
    max-connections: 500 #---最大链接数----#

spring:
  redis:
    host: 111.203.134.35
    password: wintop-yth
    port: 6390
#    host: 127.0.0.1
#    port: 6379
#    database: 0
    pool:
      max-active: 1000 #--最大活动链接---#
      max-idle: 50      #------最大允许空闲-----#
      max-wait: 100     #--------最大等待时间-----------#
  application:
    name: wintop-carauction-service  #全部小写

# 驱动配置信息
#spring.datasource.url :  jdbc:mysql://111.203.134.35:3306/ningmengcar?characterEncoding=utf8&useSSL=false&allowMultiQueries=true
#spring.datasource.username :  ningmengcar
#spring.datasource.password :  ningmeng@car%2.0
spring.datasource.url :  jdbc:mysql://rdswg333bkv6u506y1l5o.mysql.rds.aliyuncs.com:3306/ningmeng?characterEncoding=utf8&useSSL=false&allowMultiQueries=true
spring.datasource.username :  nm
spring.datasource.password :  Nm123456
spring.datasource.driverClassName :  com.mysql.jdbc.Driver
# 初始化大小，最小，最大
spring.datasource.initialSize: 100
spring.datasource.minIdle: 50
spring.datasource.maxActive: 500
# 配置获取连接等待超时的时间
spring.datasource.maxWait: 60000
# 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
spring.datasource.timeBetweenEvictionRunsMillis: 60000
# 配置一个连接在池中最小生存的时间，单位是毫秒
spring.datasource.minEvictableIdleTimeMillis: 300000
spring.datasource.validationQuery: SELECT 1 FROM DUAL
spring.datasource.testWhileIdle: true
spring.datasource.testOnBorrow: false
spring.datasource.testOnReturn: false
# 打开PSCache，并且指定每个连接上PSCache的大小
spring.datasource.poolPreparedStatements: true
spring.datasource.maxPoolPreparedStatementPerConnectionSize: 20
# 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
spring.datasource.filters: stat,log4j
# 通过connectProperties属性来打开mergeSql功能；慢SQL记录
spring.datasource.connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
# 合并多个DruidDataSource的监控数据
spring.datasource.useGlobalDataSourceStat: true
#####################################################################################################
# mysql 属性配置
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://172.16.108.17:3306/wintop
#    username: root
#    password: wintop@2016
#  jpa:
#    show-sql: true
#####################################################################################################





#####################################################################################################
# mybatis mapper xml 配置
mybatis:
  # mybatis.type-aliases-package：指定domain类的基包，即指定其在*Mapper.xml文件中可以使用简名来代替全类名（看后边的UserMapper.xml介绍）
  type-aliases-package: com.wintop.ms.carauction.mapper,com.wintop.ms.carauction.model
  mapper-locations: classpath:mybatis/mapper/*.xml,classpath:mybatis/mapper/*/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
#####################################################################################################



#####################################################################################################
# 打印日志
logging:
  level:
    root: INFO
    org.mybatis: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.springms: DEBUG
    org.springframework.cloud: debug
#####################################################################################################







